### PR TITLE
Various clean ups and code improvements in org.eclipse.test

### PR DESCRIPTION
**Pull request by HannesWell**
This PR consists of commit improve `org.eclipse.test`:
1. Format code using the standard Eclipse-Formatter and apply basic JDT clean ups.
2. Improve and clean up the code structure.

@akurtakov is there a good way to test that this does not cause a regression or do we just have to await I-build results?
I can also split this further into smaller pieces to simplify review and they can be submitted one by one and an I-build could be awaited between each.

### CODE REVIEW

**Comment by akurtakov** [comment]
Have to wait for I build

**Comment by HannesWell** [comment]
> Have to wait for I build

Do you want to review this? Should I split it into smaller pieces that are easier to review?

**Comment by akurtakov** [comment]
I can do it on Monday. On the phone now.

**Comment by HannesWell** [comment]
> I can do it on Monday. On the phone now.

Thanks! I extract the formatting and minor clean-ups in another PR already and submitted it, so tonight's I-build will show if that works (but I expect no difficulties).

Furthermore I split the remaining commit into two to simplify the review.

**Comment by HannesWell** [comment]
The I-build results look good:
- Before: https://download.eclipse.org/eclipse/downloads/drops4/I20221103-1800/
- After: https://download.eclipse.org/eclipse/downloads/drops4/I20221104-1200/
The number of executed tests slightly increased (probably some where added), but at least it looks like there wasn't fundamental regression.

**Comment by merks** [comment]
Probably the more tests is because this was fixed:

https://github.com/eclipse-platform/eclipse.platform.ui/issues/415

**Pull request merged**
