### PR TITLE
Include source features of JDT AST and Element views in the SDK feature

### PR DESCRIPTION
**Pull request by merks**
https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/387

### CODE REVIEW

**Comment by merks** [comment]
@iloveeclipse 

I think this is failing because those two features don't specify generating a corresponding source feature in the pom.xml:

image

Before I spend time adding that, I want to be sure that you an @akurtakov are okay with this approach?

**Comment by iloveeclipse** [comment]
@akurtakov : WDYT?

**Comment by merks** [comment]
I'd rather maven publish just continue to work as before this change.  This is the most expedient mechanism to do so.  Is someone else going to fix the maven publishing besides me?  Then I can, at my leisure, see what the impact of no-source-features is on the publishing process.

**Comment by mickaelistria** [comment]
> I'd rather maven publish just continue to work as before this change. This is the most expedient mechanism to do so. Is someone else going to fix the maven publishing besides me? Then I can, at my leisure, see what the impact of no-source-features is on the publishing process.

I've reopened https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/739 which we managed to dodge so far (and that's a good thing to dodge issues rather as much as possible instead of trying to fight everything at once!), but this new occurrence IMO adds enough weigh to the proposal to make it worth being considered.
I will try to find some time to look at it soon; maybe even later today.

Another approach, that may be interesting, and not necessarily exclusive; is to have some capability to `includeAllSources` when "materializing" a p2 product. Basically adding all source bundles as optional greedy dependencies when invoking the p2 director.

**Pull request closed without merging**
