### PR TITLE
Include JDT Bytecode Outline view in the SDK feature

### PR DESCRIPTION
**Pull request by iloveeclipse**
See https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/364

### CODE REVIEW

**Comment by iloveeclipse** [comment]
```
[ERROR] Cannot resolve project dependencies:
[ERROR]   Software being installed: org.eclipse.sdk.feature.group 4.27.0.qualifier
[ERROR]   Missing requirement: org.eclipse.sdk.feature.group 4.27.0.qualifier requires 'org.eclipse.equinox.p2.iu; org.eclipse.jdt.bcoview.feature.feature.group 0.0.0' but it could not be found
```

@akurtakov : I've added the feature to the JDT UI today, does it mean we have to wait for the next SDK build to see build running though?

**Comment by iloveeclipse** [comment]
I assume this has to be merged now.
Looks like jdt.ui tests can't be executed at **SDK** build (Jenkins is fine) because of
```
Cannot complete the install because one or more required items could not be found.
	Software being installed: Java Test Plug-in 3.14.700.v20230117-1527 (org.eclipse.jdt.ui.tests 3.14.700.v20230117-1527)
	Missing requirement: Java Test Plug-in 3.14.700.v20230117-1527 (org.eclipse.jdt.ui.tests 3.14.700.v20230117-1527) requires 'osgi.bundle; org.eclipse.jdt.bcoview 0.0.0' but it could not be found
```
See https://download.eclipse.org/eclipse/downloads/drops4/I20230117-1800/testresults/ep427I-unit-cen64-gtk3-java17_linux.gtk.x86_64_17/directorLogs/director-org.eclipse.jdt.ui.tests.log

**Comment by akurtakov** [comment]
Your question came after I was done for the day :). Yes, if you rely on bundle in tests it has to be in the p2 repo and this patch does exactly that.

**Comment by iloveeclipse** [comment]
I've triggered new I Build to confirm the fix.

**Pull request merged**
