### PR TITLE
Fix .eclipseproduct version and add a test for it (#211)

### PR DESCRIPTION
**Pull request by iloveeclipse**
The fail will look like:
```
java.lang.AssertionError: Product version doesn't match version of the
platform expected:<4.28.0> but was:<4.26.0>
```

Fixes https://github.com/eclipse-platform/eclipse.platform.releng/issues/211

### CODE REVIEW

**Comment by laeubi** [comment]
@iloveeclipse is `.eclipseproduct` something "PDE Standard", e.g. should Tycho support updating the version when it updates the `features.xml`?

**Comment by iloveeclipse** [comment]
> @iloveeclipse is `.eclipseproduct` something "PDE Standard", e.g. should Tycho support updating the version when it updates the `features.xml`?

I have no idea who uses that file, I've just assuming it is there for some reason.

**Comment by merks** [comment]
It's mentioned/used in a lot of places!

image

**Comment by merks** [comment]
Note that I don't see the EPP package's products (nor the Oomph Installer product) with such a marker file though...

**Pull request merged**
