### PR TITLE
Remove includes of lucene from the help feature

### PR DESCRIPTION
**Pull request by merks**
https://github.com/eclipse-platform/eclipse.platform.releng/issues/230

### CODE REVIEW

**Comment by merks** [comment]
@akurtakov 

I'm not sure this build tests much of anything...  😢

**Comment by akurtakov** [comment]
Correct this repo doesn't contain anything non-releng so no tests.

**Comment by akurtakov** [comment]
This came from some other repo change . It's already visible in last I-build https://download.eclipse.org/eclipse/downloads/drops4/I20230613-1800/buildlogs/reporeports/reports/versionChecks.html so please bump.

**Comment by merks** [comment]
@akurtakov 

So it only needs a qualifier force, not a minor increment, right?

**Comment by akurtakov** [comment]
As we are no longer including fixed versions in the feature minor bump is probably better.

**Comment by akurtakov** [comment]
> @akurtakov
> 
> Just to be sure because we all get way too much mail. The thing needing the increment is the org.eclipse.test feature while the feature I changed, org.eclipse.help, seems fine.

Yes.

**Pull request merged**
